INSERT INTO sources (
    name,
    slug,
    source_type,
    base_url,
    list_url,
    parser_key,
    automation_mode,
    authority_tier,
    privacy_risk,
    context_enabled,
    auto_publish_allowed,
    attribution_note,
    poll_frequency,
    is_active
) VALUES (
    'Wareham Media Meeting Recordings',
    'wareham-media-recordings',
    'recordings',
    'https://www.warehammedia.org',
    'https://www.warehammedia.org/wp-json/wp/v2/posts',
    'wareham_media_recordings',
    'context_only',
    'community_media',
    'low',
    1,
    0,
    'Wareham Media meeting-recording posts used for automated follow-through context.',
    'daily',
    1
)
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    source_type = VALUES(source_type),
    base_url = VALUES(base_url),
    list_url = VALUES(list_url),
    parser_key = VALUES(parser_key),
    automation_mode = VALUES(automation_mode),
    authority_tier = VALUES(authority_tier),
    privacy_risk = VALUES(privacy_risk),
    context_enabled = VALUES(context_enabled),
    auto_publish_allowed = VALUES(auto_publish_allowed),
    attribution_note = VALUES(attribution_note),
    poll_frequency = VALUES(poll_frequency),
    is_active = VALUES(is_active);
